server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hotel_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hotel_pass123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}
